# Generated by Django 3.2.20 on 2023-07-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.PositiveIntegerField(),
        ),
    ]
